# Site settings
title: Himanshu Shukla
email: himanshu.s924@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Built with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shuklahimanshu.github.io" # the base hostname & protocol for your site
twitter_username: _shuklahimanshu
github_username:  shuklahimanshu

# Build settings
markdown: kramdown
